DROP TABLE demo.Country;
DROP SCHEMA demo;
GO

CREATE SCHEMA demo;
GO

CREATE TABLE demo.Country (
  Id INT NOT NULL,
  Name VARCHAR(80) NOT NULL,
  NiceName VARCHAR(80) NOT NULL,
  IsoCode VARCHAR(3) DEFAULT NULL,
  NumCode INT DEFAULT NULL,
  PhoneCode INT NOT NULL,
  PRIMARY KEY (Id)
);
GO

INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (1,'AFGHANISTAN','Afghanistan','AFG',4,93);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (2,'ALBANIA','Albania','ALB',8,355);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (3,'ALGERIA','Algeria','DZA',12,213);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (4,'AMERICAN SAMOA','American Samoa','ASM',16,1684);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (5,'ANDORRA','Andorra','AND',20,376);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (6,'ANGOLA','Angola','AGO',24,244);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (7,'ANGUILLA','Anguilla','AIA',660,1264);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (8,'ANTARCTICA','Antarctica',NULL,NULL,0);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (9,'ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG',28,1268);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (10,'ARGENTINA','Argentina','ARG',32,54);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (11,'ARMENIA','Armenia','ARM',51,374);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (12,'ARUBA','Aruba','ABW',533,297);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (13,'AUSTRALIA','Australia','AUS',36,61);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (14,'AUSTRIA','Austria','AUT',40,43);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (15,'AZERBAIJAN','Azerbaijan','AZE',31,994);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (16,'BAHAMAS','Bahamas','BHS',44,1242);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (17,'BAHRAIN','Bahrain','BHR',48,973);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (18,'BANGLADESH','Bangladesh','BGD',50,880);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (19,'BARBADOS','Barbados','BRB',52,1246);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (20,'BELARUS','Belarus','BLR',112,375);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (21,'BELGIUM','Belgium','BEL',56,32);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (22,'BELIZE','Belize','BLZ',84,501);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (23,'BENIN','Benin','BEN',204,229);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (24,'BERMUDA','Bermuda','BMU',60,1441);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (25,'BHUTAN','Bhutan','BTN',64,975);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (26,'BOLIVIA','Bolivia','BOL',68,591);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (27,'BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH',70,387);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (28,'BOTSWANA','Botswana','BWA',72,267);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (29,'BOUVET ISLAND','Bouvet Island',NULL,NULL,0);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (30,'BRAZIL','Brazil','BRA',76,55);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (31,'BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL,246);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (32,'BRUNEI DARUSSALAM','Brunei Darussalam','BRN',96,673);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (33,'BULGARIA','Bulgaria','BGR',100,359);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (34,'BURKINA FASO','Burkina Faso','BFA',854,226);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (35,'BURUNDI','Burundi','BDI',108,257);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (36,'CAMBODIA','Cambodia','KHM',116,855);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (37,'CAMEROON','Cameroon','CMR',120,237);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (38,'CANADA','Canada','CAN',124,1);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (39,'CAPE VERDE','Cape Verde','CPV',132,238);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (40,'CAYMAN ISLANDS','Cayman Islands','CYM',136,1345);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (41,'CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF',140,236);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (42,'CHAD','Chad','TCD',148,235);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (43,'CHILE','Chile','CHL',152,56);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (44,'CHINA','China','CHN',156,86);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (45,'CHRISTMAS ISLAND','Christmas Island',NULL,NULL,61);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (46,'COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL,672);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (47,'COLOMBIA','Colombia','COL',170,57);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (48,'COMOROS','Comoros','COM',174,269);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (49,'CONGO','Congo','COG',178,242);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (50,'CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD',180,242);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (51,'COOK ISLANDS','Cook Islands','COK',184,682);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (52,'COSTA RICA','Costa Rica','CRI',188,506);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (53,'COTE D''IVOIRE','Cote D''Ivoire','CIV',384,225);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (54,'CROATIA','Croatia','HRV',191,385);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (55,'CUBA','Cuba','CUB',192,53);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (56,'CYPRUS','Cyprus','CYP',196,357);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (57,'CZECH REPUBLIC','Czech Republic','CZE',203,420);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (58,'DENMARK','Denmark','DNK',208,45);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (59,'DJIBOUTI','Djibouti','DJI',262,253);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (60,'DOMINICA','Dominica','DMA',212,1767);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (61,'DOMINICAN REPUBLIC','Dominican Republic','DOM',214,1809);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (62,'ECUADOR','Ecuador','ECU',218,593);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (63,'EGYPT','Egypt','EGY',818,20);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (64,'EL SALVADOR','El Salvador','SLV',222,503);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (65,'EQUATORIAL GUINEA','Equatorial Guinea','GNQ',226,240);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (66,'ERITREA','Eritrea','ERI',232,291);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (67,'ESTONIA','Estonia','EST',233,372);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (68,'ETHIOPIA','Ethiopia','ETH',231,251);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (69,'FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK',238,500);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (70,'FAROE ISLANDS','Faroe Islands','FRO',234,298);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (71,'FIJI','Fiji','FJI',242,679);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (72,'FINLAND','Finland','FIN',246,358);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (73,'FRANCE','France','FRA',250,33);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (74,'FRENCH GUIANA','French Guiana','GUF',254,594);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (75,'FRENCH POLYNESIA','French Polynesia','PYF',258,689);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (76,'FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL,0);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (77,'GABON','Gabon','GAB',266,241);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (78,'GAMBIA','Gambia','GMB',270,220);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (79,'GEORGIA','Georgia','GEO',268,995);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (80,'GERMANY','Germany','DEU',276,49);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (81,'GHANA','Ghana','GHA',288,233);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (82,'GIBRALTAR','Gibraltar','GIB',292,350);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (83,'GREECE','Greece','GRC',300,30);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (84,'GREENLAND','Greenland','GRL',304,299);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (85,'GRENADA','Grenada','GRD',308,1473);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (86,'GUADELOUPE','Guadeloupe','GLP',312,590);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (87,'GUAM','Guam','GUM',316,1671);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (88,'GUATEMALA','Guatemala','GTM',320,502);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (89,'GUINEA','Guinea','GIN',324,224);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (90,'GUINEA-BISSAU','Guinea-Bissau','GNB',624,245);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (91,'GUYANA','Guyana','GUY',328,592);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (92,'HAITI','Haiti','HTI',332,509);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (93,'HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL,0);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (94,'HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT',336,39);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (95,'HONDURAS','Honduras','HND',340,504);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (96,'HONG KONG','Hong Kong','HKG',344,852);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (97,'HUNGARY','Hungary','HUN',348,36);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (98,'ICELAND','Iceland','ISL',352,354);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (99,'INDIA','India','IND',356,91);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (100,'INDONESIA','Indonesia','IDN',360,62);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (101,'IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN',364,98);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (102,'IRAQ','Iraq','IRQ',368,964);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (103,'IRELAND','Ireland','IRL',372,353);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (104,'ISRAEL','Israel','ISR',376,972);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (105,'ITALY','Italy','ITA',380,39);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (106,'JAMAICA','Jamaica','JAM',388,1876);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (107,'JAPAN','Japan','JPN',392,81);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (108,'JORDAN','Jordan','JOR',400,962);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (109,'KAZAKHSTAN','Kazakhstan','KAZ',398,7);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (110,'KENYA','Kenya','KEN',404,254);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (111,'KIRIBATI','Kiribati','KIR',296,686);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (112,'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','Korea, Democratic People''s Republic of','PRK',408,850);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (113,'KOREA, REPUBLIC OF','Korea, Republic of','KOR',410,82);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (114,'KUWAIT','Kuwait','KWT',414,965);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (115,'KYRGYZSTAN','Kyrgyzstan','KGZ',417,996);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (116,'LAO PEOPLE''S DEMOCRATIC REPUBLIC','Lao People''s Democratic Republic','LAO',418,856);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (117,'LATVIA','Latvia','LVA',428,371);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (118,'LEBANON','Lebanon','LBN',422,961);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (119,'LESOTHO','Lesotho','LSO',426,266);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (120,'LIBERIA','Liberia','LBR',430,231);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (121,'LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY',434,218);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (122,'LIECHTENSTEIN','Liechtenstein','LIE',438,423);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (123,'LITHUANIA','Lithuania','LTU',440,370);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (124,'LUXEMBOURG','Luxembourg','LUX',442,352);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (125,'MACAO','Macao','MAC',446,853);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (126,'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD',807,389);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (127,'MADAGASCAR','Madagascar','MDG',450,261);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (128,'MALAWI','Malawi','MWI',454,265);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (129,'MALAYSIA','Malaysia','MYS',458,60);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (130,'MALDIVES','Maldives','MDV',462,960);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (131,'MALI','Mali','MLI',466,223);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (132,'MALTA','Malta','MLT',470,356);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (133,'MARSHALL ISLANDS','Marshall Islands','MHL',584,692);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (134,'MARTINIQUE','Martinique','MTQ',474,596);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (135,'MAURITANIA','Mauritania','MRT',478,222);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (136,'MAURITIUS','Mauritius','MUS',480,230);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (137,'MAYOTTE','Mayotte',NULL,NULL,269);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (138,'MEXICO','Mexico','MEX',484,52);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (139,'MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM',583,691);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (140,'MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA',498,373);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (141,'MONACO','Monaco','MCO',492,377);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (142,'MONGOLIA','Mongolia','MNG',496,976);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (143,'MONTSERRAT','Montserrat','MSR',500,1664);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (144,'MOROCCO','Morocco','MAR',504,212);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (145,'MOZAMBIQUE','Mozambique','MOZ',508,258);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (146,'MYANMAR','Myanmar','MMR',104,95);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (147,'NAMIBIA','Namibia','NAM',516,264);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (148,'NAURU','Nauru','NRU',520,674);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (149,'NEPAL','Nepal','NPL',524,977);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (150,'NETHERLANDS','Netherlands','NLD',528,31);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (151,'NETHERLANDS ANTILLES','Netherlands Antilles','ANT',530,599);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (152,'NEW CALEDONIA','New Caledonia','NCL',540,687);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (153,'NEW ZEALAND','New Zealand','NZL',554,64);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (154,'NICARAGUA','Nicaragua','NIC',558,505);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (155,'NIGER','Niger','NER',562,227);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (156,'NIGERIA','Nigeria','NGA',566,234);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (157,'NIUE','Niue','NIU',570,683);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (158,'NORFOLK ISLAND','Norfolk Island','NFK',574,672);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (159,'NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP',580,1670);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (160,'NORWAY','Norway','NOR',578,47);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (161,'OMAN','Oman','OMN',512,968);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (162,'PAKISTAN','Pakistan','PAK',586,92);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (163,'PALAU','Palau','PLW',585,680);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (164,'PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL,970);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (165,'PANAMA','Panama','PAN',591,507);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (166,'PAPUA NEW GUINEA','Papua New Guinea','PNG',598,675);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (167,'PARAGUAY','Paraguay','PRY',600,595);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (168,'PERU','Peru','PER',604,51);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (169,'PHILIPPINES','Philippines','PHL',608,63);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (170,'PITCAIRN','Pitcairn','PCN',612,0);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (171,'POLAND','Poland','POL',616,48);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (172,'PORTUGAL','Portugal','PRT',620,351);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (173,'PUERTO RICO','Puerto Rico','PRI',630,1787);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (174,'QATAR','Qatar','QAT',634,974);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (175,'REUNION','Reunion','REU',638,262);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (176,'ROMANIA','Romania','ROM',642,40);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (177,'RUSSIAN FEDERATION','Russian Federation','RUS',643,70);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (178,'RWANDA','Rwanda','RWA',646,250);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (179,'SAINT HELENA','Saint Helena','SHN',654,290);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (180,'SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA',659,1869);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (181,'SAINT LUCIA','Saint Lucia','LCA',662,1758);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (182,'SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM',666,508);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (183,'SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT',670,1784);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (184,'SAMOA','Samoa','WSM',882,684);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (185,'SAN MARINO','San Marino','SMR',674,378);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (186,'SAO TOME AND PRINCIPE','Sao Tome and Principe','STP',678,239);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (187,'SAUDI ARABIA','Saudi Arabia','SAU',682,966);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (188,'SENEGAL','Senegal','SEN',686,221);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (189,'SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL,381);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (190,'SEYCHELLES','Seychelles','SYC',690,248);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (191,'SIERRA LEONE','Sierra Leone','SLE',694,232);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (192,'SINGAPORE','Singapore','SGP',702,65);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (193,'SLOVAKIA','Slovakia','SVK',703,421);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (194,'SLOVENIA','Slovenia','SVN',705,386);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (195,'SOLOMON ISLANDS','Solomon Islands','SLB',90,677);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (196,'SOMALIA','Somalia','SOM',706,252);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (197,'SOUTH AFRICA','South Africa','ZAF',710,27);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (198,'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands',NULL,NULL,0);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (199,'SPAIN','Spain','ESP',724,34);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (200,'SRI LANKA','Sri Lanka','LKA',144,94);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (201,'SUDAN','Sudan','SDN',736,249);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (202,'SURINAME','Suriname','SUR',740,597);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (203,'SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM',744,47);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (204,'SWAZILAND','Swaziland','SWZ',748,268);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (205,'SWEDEN','Sweden','SWE',752,46);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (206,'SWITZERLAND','Switzerland','CHE',756,41);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (207,'SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR',760,963);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (208,'TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN',158,886);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (209,'TAJIKISTAN','Tajikistan','TJK',762,992);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (210,'TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA',834,255);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (211,'THAILAND','Thailand','THA',764,66);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (212,'TIMOR-LESTE','Timor-Leste',NULL,NULL,670);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (213,'TOGO','Togo','TGO',768,228);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (214,'TOKELAU','Tokelau','TKL',772,690);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (215,'TONGA','Tonga','TON',776,676);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (216,'TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO',780,1868);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (217,'TUNISIA','Tunisia','TUN',788,216);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (218,'TURKEY','Turkey','TUR',792,90);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (219,'TURKMENISTAN','Turkmenistan','TKM',795,7370);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (220,'TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA',796,1649);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (221,'TUVALU','Tuvalu','TUV',798,688);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (222,'UGANDA','Uganda','UGA',800,256);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (223,'UKRAINE','Ukraine','UKR',804,380);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (224,'UNITED ARAB EMIRATES','United Arab Emirates','ARE',784,971);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (225,'UNITED KINGDOM','United Kingdom','GBR',826,44);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (226,'UNITED STATES','United States','USA',840,1);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (227,'UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL,1);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (228,'URUGUAY','Uruguay','URY',858,598);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (229,'UZBEKISTAN','Uzbekistan','UZB',860,998);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (230,'VANUATU','Vanuatu','VUT',548,678);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (231,'VENEZUELA','Venezuela','VEN',862,58);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (232,'VIET NAM','Viet Nam','VNM',704,84);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (233,'VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB',92,1284);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (234,'VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR',850,1340);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (235,'WALLIS AND FUTUNA','Wallis and Futuna','WLF',876,681);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (236,'WESTERN SAHARA','Western Sahara','ESH',732,212);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (237,'YEMEN','Yemen','YEM',887,967);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (238,'ZAMBIA','Zambia','ZMB',894,260);
INSERT INTO demo.Country (Id,Name,NiceName,IsoCode,NumCode,PhoneCode) VALUES (239,'ZIMBABWE','Zimbabwe','ZWE',716,263);