DROP USER evently CASCADE;

CREATE USER evently IDENTIFIED BY evently;

GRANT connect TO evently;
GRANT resource TO evently;
GRANT create session TO evently;

GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.ATTENDEES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.EVENTS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.EVENT_STATISTICS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.INBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.INBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.OUTBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.OUTBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON ATTENDANCE.TICKETS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENTS.CATEGORIES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENTS.EVENTS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENTS.INBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENTS.INBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENTS.OUTBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENTS.OUTBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENTS.TICKET_TYPES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.CUSTOMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.EVENTS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.INBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.INBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.ORDERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.ORDER_ITEMS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.OUTBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.OUTBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.PAYMENTS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.TICKETS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON TICKETING.TICKET_TYPES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.INBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.INBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.OUTBOX_MESSAGES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.OUTBOX_MESSAGE_CONSUMERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.PERMISSIONS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.ROLES TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.ROLE_PERMISSIONS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.USERS TO evently;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS.USER_ROLES TO evently;

COMMIT;

/*
BEGIN
  FOR t IN (SELECT owner, object_name, object_type FROM all_objects WHERE owner IN ('ATTENDANCE', 'EVENTS', 'TICKETING', 'USERS') AND object_type IN ('TABLE','VIEW','PROCEDURE','FUNCTION','PACKAGE') ORDER BY owner, object_name) LOOP
    IF t.object_type IN ('TABLE','VIEW') THEN
      --EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE, INSERT, DELETE ON '||t.owner||'.'||t.object_name||' TO evently;';
      DBMS_OUTPUT.put_line('GRANT SELECT, UPDATE, INSERT, DELETE ON '||t.owner||'.'||t.object_name||' TO evently;');
    ELSIF t.object_type IN ('PROCEDURE','FUNCTION','PACKAGE') THEN
      --EXECUTE IMMEDIATE 'GRANT EXECUTE ON '||t.owner||'.'||t.object_name||' TO evently;';
      DBMS_OUTPUT.put_line('GRANT EXECUTE ON '||t.owner||'.'||t.object_name||' TO evently;');
    END IF;
  END LOOP;
END;
*/
